import type { BlogPost } from '@/types';

export const blogPosts: BlogPost[] = [
  {
    id: '1',
    title: 'Mastering Server Components in Next.js 14',
    date: 'October 26, 2023',
    summary: 'A deep dive into Next.js Server Components, exploring their benefits, use cases, and best practices for modern web development.',
    slug: 'mastering-server-components-nextjs-14',
    category: 'Next.js',
    imageUrl: 'https://placehold.co/600x400.png',
    altText: 'Abstract representation of server and client components interacting.',
    imageHint: 'tech abstract',
  },
  {
    id: '2',
    title: 'The Future of UI/UX with AI',
    date: 'November 15, 2023',
    summary: 'Exploring how artificial intelligence is reshaping user interface and user experience design, from personalization to generative UIs.',
    slug: 'future-of-ui-ux-with-ai',
    category: 'AI & Design',
    imageUrl: 'https://placehold.co/600x400.png',
    altText: 'Futuristic UI design with glowing lines and AI-related icons.',
    imageHint: 'software interface',
  },
  {
    id: '3',
    title: 'Clean Code Principles for Junior Developers',
    date: 'December 05, 2023',
    summary: 'Essential clean code principles every junior developer should know to write maintainable, readable, and efficient code.',
    slug: 'clean-code-principles-junior-devs',
    category: 'Software Development',
    imageUrl: 'https://placehold.co/600x400.png',
    altText: 'A developer working on a laptop with lines of code visible on the screen.',
    imageHint: 'coding screen',
  },
  {
    id: '4',
    title: 'Advanced Tailwind CSS Techniques',
    date: 'January 10, 2024',
    summary: 'Unlock the full potential of Tailwind CSS with advanced techniques for responsive design, custom theming, and performance optimization.',
    slug: 'advanced-tailwind-css-techniques',
    category: 'Frontend',
    imageUrl: 'https://placehold.co/600x400.png',
    altText: 'A vibrant abstract design representing Tailwind CSS utility classes.',
    imageHint: 'abstract design',
  },
  {
    id: '5',
    title: 'Building Scalable APIs with Genkit',
    date: 'February 22, 2024',
    summary: 'Learn how to leverage Genkit to build robust and scalable APIs, focusing on best practices for AI integration and data handling.',
    slug: 'scalable-apis-with-genkit',
    category: 'Backend & AI',
    imageUrl: 'https://placehold.co/600x400.png',
    altText: 'Network diagram illustrating API connections and data flow.',
    imageHint: 'network diagram',
  },
  {
    id: '6',
    title: 'Optimizing React Performance: A Comprehensive Guide',
    date: 'March 05, 2024',
    summary: 'A comprehensive guide to optimizing React application performance, covering memoization, code splitting, and virtual DOM.',
    slug: 'optimizing-react-performance',
    category: 'React',
    imageUrl: 'https://placehold.co/600x400.png',
    altText: 'A graph showing performance improvement over time.',
    imageHint: 'performance graph',
  },
];
